[package]
name = "rust-ffi-example"
version = "0.1.0"
authors = ["Rodgers <cptrodgers@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_ffi_example"
crate-type = ["lib", "cdylib"]

[dependencies]
